image:
  repository: rancher/rancher-webhook
  tag: v0.11.0-rc.9
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
    imagePullSecrets: []
  hostNetwork: false

mcm:
  enabled: true

# tolerations for the webhook deployment. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more info
tolerations: []
nodeSelector: {}

## PriorityClassName assigned to deployment.
priorityClassName: ""

# port assigns which port to use when running rancher-webhook
port: 9443

# Parameters for authenticating the kube-apiserver.
auth:
  # CA for authenticating kube-apiserver client certs. If empty, client connections will not be authenticated.
  # Must be base64-encoded.
  clientCA: ""
  # Allowlist of CNs for kube-apiserver client certs. If empty, any cert signed by the CA provided in clientCA will be accepted.
  allowedCNs: []

replicaCount: 1

resources: {}

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - rancher-webhook
        topologyKey: kubernetes.io/hostname

podDisruptionBudget:
  enabled: false
  minAvailable: 1
